# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 723dbe480a711babb3d965634207e3f3b4d5534ac886cf76a13a36e5c3eb4faf6c38604652ed1a05da3c0ba7bd3367bca80ec6676f515fecaa92ef2b2e58d1aa

test:
  secret_key_base: 08c8cef9dbfd573a71f190bc5272d53212767afd74d00cbd2dd9d88f34916dbce37ba1684307f95a3e97605aa1b2fa3176e4958dc25929f92898d826dd31d360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
